#!/usr/bin/ruby

require "yui/compressor"

TEMPLATING_RULES = [
	["\"", "'"]
]

OUTPUT = File.open('../src/ConfigurationTemplate.h', 'w')

def process_html
    f = File.open 'configuration-template.html', 'r'
    compressor = YUI::CssCompressor.new
    
    OUTPUT.puts '//'
    OUTPUT.puts '// Do not edit this file, generated code.'
    OUTPUT.puts '//'
    OUTPUT.puts ''
    
    text = nil
    f.each_line do |line|
        if line.start_with? '<!--'
            if text
                OUTPUT.puts text + '";'
            end
            text = ''
            text += 'const char HTTP_' + line.split(' ')[1] + '[] PROGMEM = "'
        else
	        TEMPLATING_RULES.each { |rule|
		        line.gsub! rule[0], rule[1]
	        }
	        text += compressor.compress line
	    end 
	 end
	 OUTPUT.close
end

process_html()
